name: FakeStore API Test Workflow

on:
  push:
    branches: [ main ]
    paths:
      - 'src/test/resources/features/**'
      - 'src/test/java/TestRunner.java'
      - 'pom.xml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/test/resources/features/**'
      - 'src/test/java/TestRunner.java'
      - 'pom.xml'

jobs:
  run-api-tests:
    name: ðŸš€ Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3


      - name: â˜• Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: ðŸ’¾ Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name:  Run Karate API tests
        run: mvn test

      - name: ðŸ“¤ Upload Karate HTML reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: karate-reports
          path: FakeStoreAPI/target/karate-reports
